#############################################################################
# Makefile for building: NPC-Handler.app/Contents/MacOS/NPC-Handler
# Generated by qmake (3.1) (Qt 6.2.4)
# Project:  ../NPC-Handler/NPC-Handler.pro
# Template: app
# Command: /Applications/Qt/6.2.4/macos/bin/qmake -o NPC-Handler.xcodeproj/project.pbxproj ../NPC-Handler/NPC-Handler.pro -spec macx-xcode -qtconf /Applications/Qt/6.2.4/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=854X7K7DLQ
#############################################################################

MAKEFILE      = project.pbxproj

EQ            = =

QMAKE    = /Applications/Qt/6.2.4/macos/bin/qmake
NPC-Handler.xcodeproj/project.pbxproj: ../NPC-Handler/NPC-Handler.pro /Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/qmake.conf /Applications/Qt/6.2.4/ios/mkspecs/features/spec_pre.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/qdevice.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/features/device_config.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/unix.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/mac.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/uikit.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/ios.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/sanitize.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/gcc-base.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/gcc-base-mac.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/clang.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/clang-mac.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/uikit/clang.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/common/uikit/qmake.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/qconfig.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_freetype.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_harfbuzz.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_libpng.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_pcre2.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_concurrent.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_core.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_core_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_entrypoint_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_gui.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_gui_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_help.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_help_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsanimation.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssettings.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssettings_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssharedimage.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_linguist.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_linguist_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_network.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_network_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_opengl.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_openglwidgets.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_printsupport.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qml.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qml_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcore.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldom_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmltest.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quick.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quick_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicklayouts.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_sql.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_sql_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svg.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svg_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svgwidgets.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_testlib.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_tools_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uitools.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_widgets.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_xml.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_xml_private.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qgif.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qico.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qios.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		/Applications/Qt/6.2.4/ios/mkspecs/features/qt_functions.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/qt_config.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/qmake.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/macx-xcode/qmake.conf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/Applications/Qt/6.2.4/ios/mkspecs/features/exclusive_builds.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/sdk.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/sdk.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/toolchain.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/toolchain.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/default_pre.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/default_pre.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/default_pre.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/resolve_config.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/resolve_config.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/default_post.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/default_post.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/default_post.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/objective_c.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/lrelease.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/qml_debug.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/entrypoint.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/mac.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/bitcode.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/warn_on.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/qt.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/resources_functions.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/resources.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/moc.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/unix/opengl.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uic.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/unix/thread.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/qmake_use.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/file_copies.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/rez.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/mac/asset_catalogs.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/testcase_targets.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/testcase_targets.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/exceptions.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/yacc.prf \
		/Applications/Qt/6.2.4/ios/mkspecs/features/lex.prf \
		../NPC-Handler/NPC-Handler.pro \
		/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard \
		../NPC-Handler/resources.qrc \
		qmake_qmake_qm_files.qrc \
		/Applications/Qt/6.2.4/ios/plugins/platforms/libqios_debug.prl \
		/Applications/Qt/6.2.4/ios/plugins/iconengines/libqsvgicon_debug.prl \
		/Applications/Qt/6.2.4/ios/plugins/imageformats/libqgif_debug.prl \
		/Applications/Qt/6.2.4/ios/plugins/imageformats/libqico_debug.prl \
		/Applications/Qt/6.2.4/ios/plugins/imageformats/libqjpeg_debug.prl \
		/Applications/Qt/6.2.4/ios/plugins/imageformats/libqsvg_debug.prl \
		/Applications/Qt/6.2.4/ios/lib/libQt6Widgets_debug.prl \
		/Applications/Qt/6.2.4/ios/lib/libQt6Gui_debug.prl \
		/Applications/Qt/6.2.4/ios/lib/libQt6Core_debug.prl
	$(QMAKE) -o NPC-Handler.xcodeproj/project.pbxproj ../NPC-Handler/NPC-Handler.pro -spec macx-xcode -qtconf /Applications/Qt/6.2.4/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=854X7K7DLQ
	@echo 'warning: Xcode project has been regenerated, custom settings have been lost. Use CONFIG+=no_autoqmake to prevent this behavior in the future, at the cost of requiring manual project change tracking.'
/Applications/Qt/6.2.4/ios/mkspecs/features/spec_pre.prf:
/Applications/Qt/6.2.4/ios/mkspecs/qdevice.pri:
/Applications/Qt/6.2.4/ios/mkspecs/features/device_config.prf:
/Applications/Qt/6.2.4/ios/mkspecs/common/unix.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/mac.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/uikit.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/ios.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/sanitize.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/gcc-base.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/gcc-base-mac.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/clang.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/clang-mac.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/uikit/clang.conf:
/Applications/Qt/6.2.4/ios/mkspecs/common/uikit/qmake.conf:
/Applications/Qt/6.2.4/ios/mkspecs/qconfig.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_freetype.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_harfbuzz.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_libpng.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_ext_pcre2.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_concurrent.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_core.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_core_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_entrypoint_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_gui.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_gui_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_help.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_help_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsanimation.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsanimation_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssettings.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssettings_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssharedimage.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_linguist.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_linguist_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_network.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_network_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_opengl.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_opengl_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_openglwidgets.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_printsupport.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_printsupport_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qml.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qml_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcore.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlcore_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmldom_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmltest.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quick.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quick_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicklayouts.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_sql.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_sql_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svg.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svg_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svgwidgets.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_testlib.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_testlib_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_tools_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uiplugin.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uitools.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_uitools_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_widgets.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_widgets_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_xml.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_lib_xml_private.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qcertonlybackend.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qgif.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qico.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qios.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qminimal.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qscnetworkreachability.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsecuretransportbackend.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsvg.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
/Applications/Qt/6.2.4/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
/Applications/Qt/6.2.4/ios/mkspecs/features/qt_functions.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/qt_config.prf:
/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/qmake.conf:
/Applications/Qt/6.2.4/ios/mkspecs/macx-xcode/qmake.conf:
/Applications/Qt/6.2.4/ios/mkspecs/features/spec_post.prf:
.qmake.stash:
/Applications/Qt/6.2.4/ios/mkspecs/features/exclusive_builds.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/sdk.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/sdk.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/toolchain.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/toolchain.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/default_pre.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/default_pre.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/default_pre.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/resolve_config.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/resolve_config.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/default_post.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/default_post.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/default_post.prf:
/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/features/default_post.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/objective_c.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/lrelease.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/qml_debug.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/entrypoint.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/mac.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/bitcode.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/warn_on.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/qt.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/resources_functions.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/resources.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/moc.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/unix/opengl.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uic.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/unix/thread.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/qmake_use.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/file_copies.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/rez.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/mac/asset_catalogs.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/testcase_targets.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/uikit/testcase_targets.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/exceptions.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/yacc.prf:
/Applications/Qt/6.2.4/ios/mkspecs/features/lex.prf:
../NPC-Handler/NPC-Handler.pro:
/Applications/Qt/6.2.4/ios/mkspecs/macx-ios-clang/LaunchScreen.storyboard:
../NPC-Handler/resources.qrc:
qmake_qmake_qm_files.qrc:
/Applications/Qt/6.2.4/ios/plugins/platforms/libqios_debug.prl:
/Applications/Qt/6.2.4/ios/plugins/iconengines/libqsvgicon_debug.prl:
/Applications/Qt/6.2.4/ios/plugins/imageformats/libqgif_debug.prl:
/Applications/Qt/6.2.4/ios/plugins/imageformats/libqico_debug.prl:
/Applications/Qt/6.2.4/ios/plugins/imageformats/libqjpeg_debug.prl:
/Applications/Qt/6.2.4/ios/plugins/imageformats/libqsvg_debug.prl:
/Applications/Qt/6.2.4/ios/lib/libQt6Widgets_debug.prl:
/Applications/Qt/6.2.4/ios/lib/libQt6Gui_debug.prl:
/Applications/Qt/6.2.4/ios/lib/libQt6Core_debug.prl:
qmake: FORCE
	@$(QMAKE) -o NPC-Handler.xcodeproj/project.pbxproj ../NPC-Handler/NPC-Handler.pro -spec macx-xcode -qtconf /Applications/Qt/6.2.4/ios/bin/target_qt.conf CONFIG+=debug CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug QMAKE_MAC_XCODE_SETTINGS+=qteam qteam.name=DEVELOPMENT_TEAM qteam.value=854X7K7DLQ

qmake_all: FORCE

